# Prebuilt mountthor release artifacts.
#
# These are official prebuilt binaries (Apache-2.0), not built from source here.
#
# Source of truth: https://get.mountthor.com/manifest.json. We track the
# `.latest_by_platform` entries for the three platforms below — NOT the global
# `.latest` field, which the renderer floors at the last Windows-capable
# release for the benefit of old self-updating clients. Nix only consumes the
# macOS/Linux tarballs, so per-platform `latest_by_platform` is what we want.
#
# This file is regenerated by ./update.sh (run daily by
# .github/workflows/update.yml). Prefer editing that script over hand-tweaking
# this file.
#
# Only platforms with a published .tar.xz are listed (the manifest also ships
# .deb/.rpm/.zip artifacts, which are not useful as a Nix source).
{
  version = "0.3.15";

  artifacts = {
    "x86_64-linux" = {
      triple = "x86_64-unknown-linux-gnu";
      sha256 = "bfa71ceb882004ce132169caba57f6de7283407956e78ff292d380b1a6833fdf";
    };
    "aarch64-darwin" = {
      triple = "aarch64-apple-darwin";
      sha256 = "3c65367f0d19ec402a1abb2f2f5cfd51a2a8a54f0f9fbd8b567afe1735e9019a";
    };
    "x86_64-darwin" = {
      triple = "x86_64-apple-darwin";
      sha256 = "7fb001cea425188c1f9e75b3ed12702b30d8d2710692920310c237db7a15bcd5";
    };
  };
}
