# Prebuilt mountthor release artifacts.
#
# These are official prebuilt binaries (Apache-2.0), not built from source here.
#
# Source of truth: https://get.mountthor.com/manifest.json. We track the
# `.latest_by_platform` entries for the platforms below — NOT the global
# `.latest` field, which the renderer floors at the last Windows-capable
# release for the benefit of old self-updating clients. Nix only consumes the
# macOS/Linux tarballs, so per-platform `latest_by_platform` is what we want.
#
# This file is regenerated by ./update.sh (run daily by
# .github/workflows/update.yml). Prefer editing that script over hand-tweaking
# this file.
#
# Only platforms with a published .tar.xz are listed (the manifest also ships
# .deb/.rpm/.zip artifacts, which are not useful as a Nix source).
{
  version = "0.3.65";

  artifacts = {
    "x86_64-linux" = {
      triple = "x86_64-unknown-linux-gnu";
      sha256 = "122c7cad6d6e0a2e956a36771308f6480ccf81c9f80945a58661a80db4fb0b5a";
    };
    "aarch64-linux" = {
      triple = "aarch64-unknown-linux-gnu";
      sha256 = "6dee7e43c6bf66c775137a55c93de368791de21fefd364d1e1d0d2db5338f21a";
    };
    "aarch64-darwin" = {
      triple = "aarch64-apple-darwin";
      sha256 = "78dace5ab0ab5c11d3995be29cefc61fe7b10c33a22fc782bab9e62bd4240e55";
    };
    "x86_64-darwin" = {
      triple = "x86_64-apple-darwin";
      sha256 = "49cffa50b4a5b00559b9f827e0f2dc091db4ff43ebff442d7a3908469c5b5430";
    };
  };
}
