#!/usr/bin/env bash
# Refresh sources.nix to match the upstream manifest's ".latest".
#
# Pulls https://get.mountthor.com/manifest.json, finds the latest version,
# extracts the .tar.xz sha256 for each platform we package, and rewrites
# sources.nix in place. Idempotent — exits 0 with no changes when current.
#
# Requires: bash, curl, jq.
set -euo pipefail

MANIFEST_URL="${MANIFEST_URL:-https://get.mountthor.com/manifest.json}"
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
sources="$here/sources.nix"

manifest="$(curl -fsSL "$MANIFEST_URL")"
latest="$(jq -er '.latest' <<<"$manifest")"

sha_for() {
  local platform="$1"
  jq -er --arg v "$latest" --arg p "$platform" '
    .versions[] | select(.version == $v)
    | .artifacts[] | select(.platform == $p) | .sha256
  ' <<<"$manifest"
}

linux_sha="$(sha_for linux-x86_64-tarball)"
aarch64_darwin_sha="$(sha_for macos-aarch64)"
x86_64_darwin_sha="$(sha_for macos-x86_64)"

cat >"$sources" <<EOF
# Prebuilt mountthor release artifacts.
#
# Mirrors the ".latest" entry of https://get.mountthor.com/manifest.json. These
# are official prebuilt binaries (Apache-2.0), not built from source here.
#
# This file is regenerated by ./update.sh (run daily by .github/workflows/update.yml).
# Edit that script rather than tweaking this file by hand.
#
# Only platforms with a published .tar.xz are listed (the manifest also ships
# .deb/.rpm/.zip artifacts, which are not useful as a Nix source).
{
  version = "$latest";

  artifacts = {
    "x86_64-linux" = {
      triple = "x86_64-unknown-linux-gnu";
      sha256 = "$linux_sha";
    };
    "aarch64-darwin" = {
      triple = "aarch64-apple-darwin";
      sha256 = "$aarch64_darwin_sha";
    };
    "x86_64-darwin" = {
      triple = "x86_64-apple-darwin";
      sha256 = "$x86_64_darwin_sha";
    };
  };
}
EOF

echo "sources.nix pinned to mountthor v$latest"
