#!/usr/bin/env bash
# Refresh sources.nix to match the upstream manifest's per-platform latest.
#
# Pulls https://get.mountthor.com/manifest.json, picks the version we should
# ship for each of the three platforms we package, and rewrites sources.nix in
# place. Idempotent — exits 0 with no changes when current.
#
# Why per-platform and not `.latest`: the manifest's global `.latest` is
# intentionally floored at the last Windows-capable release (currently 0.3.5)
# so older self-updating clients keep working. Nix only consumes the macOS and
# Linux tarballs, so we read `.latest_by_platform` instead. macOS arm64,
# macOS x86_64, and linux-x86_64-tarball move in lockstep on each release —
# we sanity-check that and fail loudly if they ever diverge, because a single
# `version` field in sources.nix can't represent a split.
#
# Requires: bash, curl, jq.
set -euo pipefail

MANIFEST_URL="${MANIFEST_URL:-https://get.mountthor.com/manifest.json}"
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
sources="$here/sources.nix"

manifest="$(curl -fsSL "$MANIFEST_URL")"

version_for() {
  jq -er --arg p "$1" '.latest_by_platform[$p]' <<<"$manifest"
}

linux_v="$(version_for linux-x86_64-tarball)"
aarch64_darwin_v="$(version_for macos-aarch64)"
x86_64_darwin_v="$(version_for macos-x86_64)"

if [[ "$linux_v" != "$aarch64_darwin_v" || "$linux_v" != "$x86_64_darwin_v" ]]; then
  echo "update.sh: per-platform latest diverged — linux=$linux_v, macos-aarch64=$aarch64_darwin_v, macos-x86_64=$x86_64_darwin_v" >&2
  echo "update.sh: sources.nix has one version field for all three; rerun once upstream realigns or update this script to track them separately." >&2
  exit 1
fi
latest="$linux_v"

sha_for() {
  local platform="$1"
  jq -er --arg v "$latest" --arg p "$platform" '
    .versions[] | select(.version == $v)
    | .artifacts[] | select(.platform == $p) | .sha256
  ' <<<"$manifest"
}

linux_sha="$(sha_for linux-x86_64-tarball)"
aarch64_darwin_sha="$(sha_for macos-aarch64)"
x86_64_darwin_sha="$(sha_for macos-x86_64)"

cat >"$sources" <<EOF
# Prebuilt mountthor release artifacts.
#
# These are official prebuilt binaries (Apache-2.0), not built from source here.
#
# Source of truth: https://get.mountthor.com/manifest.json. We track the
# \`.latest_by_platform\` entries for the three platforms below — NOT the global
# \`.latest\` field, which the renderer floors at the last Windows-capable
# release for the benefit of old self-updating clients. Nix only consumes the
# macOS/Linux tarballs, so per-platform \`latest_by_platform\` is what we want.
#
# This file is regenerated by ./update.sh (run daily by
# .github/workflows/update.yml). Prefer editing that script over hand-tweaking
# this file.
#
# Only platforms with a published .tar.xz are listed (the manifest also ships
# .deb/.rpm/.zip artifacts, which are not useful as a Nix source).
{
  version = "$latest";

  artifacts = {
    "x86_64-linux" = {
      triple = "x86_64-unknown-linux-gnu";
      sha256 = "$linux_sha";
    };
    "aarch64-darwin" = {
      triple = "aarch64-apple-darwin";
      sha256 = "$aarch64_darwin_sha";
    };
    "x86_64-darwin" = {
      triple = "x86_64-apple-darwin";
      sha256 = "$x86_64_darwin_sha";
    };
  };
}
EOF

echo "sources.nix pinned to mountthor v$latest"
